name: build and release a new package version
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore logzio-dotnet.sln
      - name: Build and release package
        working-directory: ./package
        run: |
          build-nlog.bat ${{ github.event.release.tag_name }}
          build-log4net.bat ${{ github.event.release.tag_name }}
