name: build and release a new package version

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore logzio-dotnet.sln
      
      - name: Build projects for net8.0
        working-directory: ./src
        run: |
          dotnet build logzio-dotnet.sln -c Release -f net8.0
      
      - name: Build projects for net6.0
        working-directory: ./src
        run: |
          dotnet build logzio-dotnet.sln -c Release -f net6.0
      
      - name: Pack and release Log4netShipper for net8.0
        working-directory: ./src/Log4netShipper
        run: |
          dotnet pack --configuration Release -p:TargetFramework=net8.0
          dotnet nuget push "./bin/Release/Logzio.DotNet.Log4net.${{ github.event.release.tag_name }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
      - name: Pack and release Log4netShipper for net6.0
        working-directory: ./src/Log4netShipper
        run: |
          dotnet pack --configuration Release -p:TargetFramework=net6.0
          dotnet nuget push "./bin/Release/Logzio.DotNet.Log4net.${{ github.event.release.tag_name }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
      - name: Pack and release NLogShipper for net8.0
        working-directory: ./src/NLogShipper
        run: |
          dotnet pack --configuration Release -p:TargetFramework=net8.0
          dotnet nuget push "./bin/Release/Logzio.DotNet.NLog.${{ github.event.release.tag_name }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
      - name: Pack and release NLogShipper for net6.0
        working-directory: ./src/NLogShipper
        run: |
          dotnet pack --configuration Release -p:TargetFramework=net6.0
          dotnet nuget push "./bin/Release/Logzio.DotNet.NLog.${{ github.event.release.tag_name }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
