name: unit and integration testing for dotnet package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.0', '3.0', '5.0', '6.0', '7.0', '8.0']
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore logzio-dotnet.sln
      - name: Build package
        working-directory: ./src
        run: dotnet build logzio-dotnet.sln /p:Configuration=Release
      - name: Run tests
        working-directory: ./src
        run: |
          dotnet test ./UnitTests/UnitTests.csproj
          dotnet test ./IntegrationTests/IntegrationTests.csproj
